[package]
name = "free_structure"
version = "0.1.0"
edition = "2024"

[dependencies]
proptest = { version = "1.6.0", features = ["proptest-macro"] }
rand = "0.9.0"

[dev-dependencies]
criterion = { version = "0.5.1", features = ["html_reports"] }

[[bench]]
name = "hashmap_bench"
harness = false
